
export class Student
{
    
     Email ?: string;
     Password ?: string;
     Firstname : string;
     Lastname : string;
     Nummer : string;
     Anschrift : string;
     Geschecht : string;
     Bild : string;

     Student_Email_Uid ? : string
     Student_Id_ref ? : string;
     MatrikulNummer ? : string
     Studiengang_Id ? : string
     StudiengangName ? : string
     
    
     
    





}